set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[7]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[3]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[0]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[1]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[2]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[4]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[5]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[6]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[0]}]
set_property MARK_DEBUG true [get_nets inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tlast]
set_property MARK_DEBUG true [get_nets inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tvalid]
set_property MARK_DEBUG true [get_nets inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tuser]
set_property MARK_DEBUG true [get_nets inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tvalid]
set_property MARK_DEBUG true [get_nets inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tlast]
set_property MARK_DEBUG true [get_nets inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tready]
set_property MARK_DEBUG true [get_nets inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tuser]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[7]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[5]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[6]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[3]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[4]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[1]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[2]}]


set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_rxd_tdata[4]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_rxd_tdata[0]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_rxd_tdata[1]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_rxd_tdata[2]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_rxd_tdata[3]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_rxd_tdata[5]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_rxd_tdata[6]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_rxd_tdata[7]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_txd_tdata[0]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_txd_tdata[1]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_txd_tdata[2]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_txd_tdata[4]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_txd_tdata[6]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_txd_tdata[7]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_txd_tdata[5]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/axis_txd_tdata[3]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[2]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[0]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[1]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[3]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[4]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[5]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[6]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[7]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[0]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[3]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[5]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[7]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[6]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[4]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[1]}]
set_property MARK_DEBUG true [get_nets {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[2]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list inst/design_mips_i/clk_wiz/inst/clk_router]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[0]} {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[1]} {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[2]} {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[3]} {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[4]} {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[5]} {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[6]} {inst/design_mips_i/router_0/inst/router_inst/os_txd_tdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[0]} {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[1]} {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[2]} {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[3]} {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[4]} {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[5]} {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[6]} {inst/design_mips_i/router_0/inst/router_inst/os_rxd_tdata[7]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/inst/tri_mode_ethernet_mac_i/rgmii_interface/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[0]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[1]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[2]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[3]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[4]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[5]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[6]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tdata[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tlast]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tuser]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/rx_axis_mac_tvalid]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/inst/tri_mode_ethernet_mac_support_clocking_i/gtx_clk_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 8 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[0]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[1]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[2]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[3]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[4]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[5]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[6]} {inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tdata[7]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 1 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tlast]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tready]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 1 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list inst/design_mips_i/router_0/inst/router_inst/port_inst_0/tri_mode_ethernet_mac_0_inst/tx_axis_mac_tvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_1]
